image: node:lts # Using node:lts is generally recommended for stability

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .next/cache/ # Cache Next.js build cache for faster subsequent builds

build_job:
  stage: build
  script:
    - npm ci # Install dependencies securely
    - npm run build # This will generate the 'out' directory if output: 'export' is set in next.config.js
  artifacts:
    paths:
      - out/ # Collect the generated 'out' directory as an artifact
    expire_in: 1 week

pages:
  stage: deploy
  script:
    # Ensure the 'public' directory exists and contains your site files.
    # If Next.js 'export' put everything into 'out', then this move is sufficient.
    - mv out public 

    # --- Gzip Compression Step ---
    # Install gzip if not already present (node:lts should have it, but useful if you switch images)
    # This line is usually not needed for node:lts, but included for completeness:
    # - apt-get update && apt-get install -y gzip 

    # Find all HTML, CSS, JS, JSON, TXT, XML, and SVG files and gzip them.
    # -f: Force overwrite any existing .gz files.
    # -k: Keep the original (uncompressed) file. This is crucial for GitLab Pages.
    # -6: Set compression level to 6 (a good balance of speed and compression).
    - find public -type f -regex '.*\.\(html\|css\|js\|json\|txt\|xml\|svg\)$' -exec gzip -f -k -6 {} \;
    # --- End Gzip Compression Step ---
    
  dependencies:
    - build_job # Ensure the build_job completes before this job
  artifacts:
    paths:
      - public # Publish the 'public' directory (now containing both original and .gz files) for GitLab Pages
  only:
    - main # Deploy only from the main branch