backend:
  name: gitlab
  repo: AWD-2069/cleanitup_nextjs # e.g., myuser/my-decap-cms-project
  auth_type: pkce
  app_id: 3d6454e719c150aab704e753209e357ee7a1e2043ceef4a4b2be28c2f37544ac # See next step for how to get this

media_folder: "public/images" # Where images uploaded via the CMS will be stored
public_folder: "/images" # The path to the public folder for images
